# Generated by Django 4.0.3 on 2022-04-21 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroup', '0002_alter_user_options_user_created_user_modified'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgmembership',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='organization.OrgMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='orgmembership',
            unique_together={('user', 'org')},
        ),
    ]
