# Generated by Django 4.0.4 on 2022-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('organization_admin', 'Administer organizations'), ('edit_all_organization', 'Edit all organizations'), ('change_open_organization', 'Change is_open field'), ('spam_organization', 'Create organization without limit')), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='is_unlisted',
            field=models.BooleanField(default=True, help_text='Organization will not be listed', verbose_name='is unlisted organization?'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_override_image',
            field=models.CharField(blank=True, default='', help_text='This image will replace the default site logo for users viewing the organization.', max_length=150, verbose_name='Logo override image'),
        ),
        migrations.AddField(
            model_name='organization',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='performance_points',
            field=models.FloatField(default=0),
        ),
    ]
