# Generated by Django 4.0.4 on 2022-06-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_options_organization_is_unlisted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='creation_date',
            new_name='created',
        ),
    ]
