# Generated by Django 4.0.4 on 2022-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_override_image',
            field=models.CharField(blank=True, default='', help_text='Link to organization logo.', max_length=256, verbose_name='Logo override image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(help_text='Displayed beside user name during contests.', max_length=64, unique=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Organization name shown in URL and also will be used for searching.', max_length=128, unique=True, verbose_name='organization slug'),
        ),
    ]
