# Generated by Django 4.0.4 on 2022-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_depth_organization_numchild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_override_image',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.CharField(blank=True, default='', help_text='Link to organization logo.', max_length=256, verbose_name='logo url'),
        ),
    ]
