# Generated by Django 4.0.4 on 2022-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_access_code_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Required joining user provide access code', verbose_name='is organization protected by an access code?'),
        ),
    ]
