# Generated by Django 4.0.4 on 2022-07-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_alter_contest_options_contest_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
    ]
