# Generated by Django 4.0.4 on 2022-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0006_alter_contest_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
    ]
