# Generated by Django 4.0.4 on 2022-09-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_options_and_more'),
        ('compete', '0009_contestproblem_frozen_attempted_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization', verbose_name='organization'),
        ),
    ]
