# Generated by Django 4.0.3 on 2022-04-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Server name, hostname-style', max_length=50, unique=True, verbose_name='judge name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('auth_key', models.CharField(help_text='A key to authenticate this judge', max_length=100, verbose_name='authentication key')),
                ('is_blocked', models.BooleanField(default=False, help_text='Whether this judge should be blocked from connecting, even if its key is correct.', verbose_name='block judge')),
                ('online', models.BooleanField(default=False, verbose_name='judge online status')),
                ('start_time', models.DateTimeField(null=True, verbose_name='judge start time')),
                ('ping', models.FloatField(null=True, verbose_name='response time')),
                ('load', models.FloatField(help_text='Load for the last minute, divided by processors to be fair.', null=True, verbose_name='system load')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last connected IP')),
            ],
            options={
                'verbose_name': 'judge',
                'verbose_name_plural': 'judges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=6, unique=True, verbose_name='short identifier')),
                ('name', models.CharField(help_text='Longer name for the language, e.g. "Python 2" or "C++11".', max_length=20, verbose_name='long name')),
                ('short_name', models.CharField(blank=True, help_text='More readable, but short, name to display publicly; e.g. "PY2" or "C++11". If left blank, it will default to the short identifier.', max_length=10, null=True, verbose_name='short name')),
                ('common_name', models.CharField(help_text='Common name for the language. For example, the common name for C++03, C++11, and C++14 would be "C++"', max_length=10, verbose_name='common name')),
                ('ace', models.CharField(help_text='Language ID for Ace.js editor highlighting, appended to "mode-" to determine the Ace JavaScript file to use, e.g., "python".', max_length=20, verbose_name='ace mode name')),
                ('pygments', models.CharField(help_text='Language ID for Pygments highlighting in source windows.', max_length=20, verbose_name='pygments name')),
                ('template', models.TextField(blank=True, help_text='Code template to display in submission editor.', verbose_name='code template')),
                ('info', models.CharField(blank=True, help_text="Do not set this unless you know what you're doing! It will override the usually more specific, judge-provided runtime info!", max_length=50, verbose_name='runtime info override')),
                ('description', models.TextField(blank=True, help_text='Use this field to inform users of quirks with your environment, additional restrictions, etc.', verbose_name='language description')),
                ('extension', models.CharField(help_text='The extension of source files, e.g., "py" or "cpp".', max_length=10, verbose_name='extension')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='runtime name')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='runtime version')),
                ('priority', models.IntegerField(default=0, verbose_name='order in which to display this runtime')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger.judge', verbose_name='judge on which this runtime exists')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger.language', verbose_name='language to which this runtime belongs')),
            ],
        ),
    ]
