# Generated by Django 4.0.3 on 2022-05-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('judger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelimit',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_limits', to='problem.problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='judge',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='judges', to='problem.problem', verbose_name='problems'),
        ),
        migrations.AddField(
            model_name='judge',
            name='runtimes',
            field=models.ManyToManyField(blank=True, related_name='judges', to='judger.language', verbose_name='judges'),
        ),
        migrations.AlterUniqueTogether(
            name='languagelimit',
            unique_together={('problem', 'language')},
        ),
    ]
