# Generated by Django 4.0.3 on 2022-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
        ('judger', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='judges', to='problem.problem', verbose_name='problems'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='runtimes',
            field=models.ManyToManyField(blank=True, related_name='judges', to='judger.language', verbose_name='judges'),
        ),
    ]
