# Generated by Django 4.0.3 on 2022-05-02 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_problem_short_circuit'),
        ('judger', '0003_alter_judge_problems_alter_judge_runtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(20.0)], verbose_name='time limit')),
                ('memory_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(65536), django.core.validators.MaxValueValidator(1048576)], verbose_name='memory limit')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger.language', verbose_name='language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_limits', to='problem.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'language-specific resource limit',
                'verbose_name_plural': 'language-specific resource limits',
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
