# Generated by Django 4.0.3 on 2022-05-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0004_languagelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='load',
            field=models.FloatField(default=None, help_text='Load for the last minute, divided by processors to be fair.', null=True, verbose_name='system load'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='ping',
            field=models.FloatField(default=None, null=True, verbose_name='response time'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='judge start time'),
        ),
    ]
