# Generated by Django 4.0.4 on 2022-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='badge name')),
                ('mini', models.URLField(blank=True, verbose_name='mini badge URL')),
                ('full_size', models.URLField(blank=True, verbose_name='full size badge URL')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Show to banned user in login page.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_rank',
            field=models.CharField(choices=[('banned', 'Banned User'), ('user', 'Normal User'), ('setter', 'Problem Setter'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=10, verbose_name='display rank'),
        ),
    ]
