# Generated by Django 4.0.4 on 2022-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_members_alter_orgmembership_user'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orgs',
            field=models.ManyToManyField(through='organization.OrgMembership', to='organization.organization'),
        ),
    ]
