# Generated by Django 4.0.4 on 2022-06-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_short_name'),
        ('userprofile', '0002_userprofile_display_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_members', related_query_name='representative_member', to='organization.organization', verbose_name='display organization'),
        ),
    ]
