# Generated by Django 4.0.3 on 2022-04-16 12:46

from django.db import migrations, models
import helpers.fileupload


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_options_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to=helpers.fileupload.PathAndRename('/avatars')),
        ),
    ]
