# Generated by Django 4.0.3 on 2022-04-19 10:45

from django.db import migrations, models
import helpers.fileupload


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to=helpers.fileupload.PathAndRename('avatar/')),
        ),
    ]
