# Generated by Django 4.0.3 on 2022-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_ranking',
            field=models.BigIntegerField(default=0),
        ),
    ]
