# Generated by Django 4.0.4 on 2022-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='partial',
            field=models.BooleanField(default=False, help_text='Allow solvers to earn points for each testcase they did right.', verbose_name='allow earning partial points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_circuit',
            field=models.BooleanField(default=False, help_text='Stop grading as soon as there is one not acceptted testcase.', verbose_name='stop on unacceptted testcase'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='submission_visibility_mode',
            field=models.CharField(choices=[('FOLLOW', "Follow bkdnOJ's setting."), ('ALWAYS', 'Users can see all submissions'), ('SOLVED', 'Users can see their own, and others if they have solved that problem'), ('ONLY_OWN', 'Users can only see their own submissions.'), ('HIDDEN', 'Submissions will never be visible.')], default='FOLLOW', help_text="Determine if users can view submissions for this problem. This is for public problems only. For problems within certain contests, please set the contest's own submission visibility setting.", max_length=16),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_limit',
            field=models.IntegerField(blank=True, default=1000000000000, null=True, verbose_name='output limit length'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_prefix',
            field=models.IntegerField(blank=True, default=200, null=True, verbose_name='output prefix length'),
        ),
    ]
