# Generated by Django 4.0.4 on 2022-06-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('problem', '0001_initial'),
        ('organization', '0002_initial'),
        ('judger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='authors',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may view, edit the problem, and will be listed as Authors on the Problem Detail page.', related_name='authored_problems', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='problem',
            name='banned_users',
            field=models.ManyToManyField(blank=True, help_text='Bans the selected users from submitting to this problem.', to='userprofile.userprofile', verbose_name='personae non gratae'),
        ),
        migrations.AddField(
            model_name='problem',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], help_text="These users may view, edit the problem, but won't be listed as Authors on the Problem Detail page.", related_name='collaborated_problems', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='problem',
            name='organizations',
            field=models.ManyToManyField(blank=True, default=[], to='organization.organization', verbose_name='organizations'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reviewers',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may only view and make submissions to the problem', related_name='reviewed_problems', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='languagelimit',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger.language', verbose_name='language'),
        ),
        migrations.AddField(
            model_name='languagelimit',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_limits', to='problem.problem', verbose_name='problem'),
        ),
        migrations.AlterUniqueTogether(
            name='languagelimit',
            unique_together={('problem', 'language')},
        ),
    ]
