# Generated by Django 4.0.3 on 2022-04-28 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='authors',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may view, edit the problem, and will be listed as Authors on the Problem Detail page.', related_name='authored_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], help_text="These users may view, edit the problem, but won't be listed as Authors on the Problem Detail page.", related_name='collaborated_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='reviewers',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may only view and make submissions to the problem', related_name='reviewed_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, default=[], related_name='shared_orgs', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='languagelimit',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.language', verbose_name='language'),
        ),
        migrations.AddField(
            model_name='languagelimit',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_limits', to='problem.problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='problemtestdataprofile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemtestcase',
            name='test_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problemtestdataprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='languagelimit',
            unique_together={('problem', 'language')},
        ),
    ]
