# Generated by Django 4.0.4 on 2022-07-14 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_alter_problem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelimit',
            name='time_limit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(20.0)], verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_organization_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If private only added, organizations may see and submit to the problem.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
