# Generated by Django 4.0.3 on 2022-04-23 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='allowed_language',
            field=models.ManyToManyField(blank=True, default=[], help_text='List of allowed submission languages.', to='runtime.language'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='authors',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may view, edit the problem, and will be listed as Authors on the Problem Detail page.', related_name='authored_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], help_text="These users may view, edit the problem, but won't be listed as Authors on the Problem Detail page.", related_name='collaborated_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reviewers',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may only view and make submissions to the problem', related_name='reviewed_problem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, default=[], to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Sources of the problem. For example: Codeforces Div.2 Round #123 - Problem D.', max_length=2048),
        ),
    ]
