# Generated by Django 4.0.4 on 2022-06-17 10:38

import django.core.validators
from django.db import migrations, models
import helpers.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestprofile',
            name='custom_checker',
            field=models.FileField(blank=True, null=True, storage=helpers.problem_data.ProblemDataStorage(), upload_to=helpers.problem_data.ProblemDataStorage(), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Custom checker script/code'),
        ),
        migrations.AlterField(
            model_name='problemtestprofile',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom', 'Custom checker (Py3)')], max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom', 'Custom checker (Py3)')], max_length=10, verbose_name='checker'),
        ),
    ]
