# Generated by Django 4.0.4 on 2022-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_alter_problemtestprofile_output_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='output_limit',
            field=models.IntegerField(blank=True, default=20000000, null=True, verbose_name='output limit length'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_prefix',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='output prefix length'),
        ),
    ]
