# Generated by Django 4.0.4 on 2022-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_alter_languagelimit_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='partial',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow solvers to earn points for each testcase they did right.', verbose_name='allow earning partial points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_circuit',
            field=models.BooleanField(db_index=True, default=False, help_text='Stop grading as soon as there is one not acceptted testcase.', verbose_name='stop on unacceptted testcase'),
        ),
    ]
