# Generated by Django 4.0.3 on 2022-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('problem', '0003_alter_problem_allowed_language_alter_problem_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='organization.organization'),
        ),
    ]
