# Generated by Django 4.0.3 on 2022-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('problem', '0004_alter_problem_shared_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(blank=True, default='', help_text="Problem's statement"),
        ),
        migrations.AlterField(
            model_name='problem',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, default=[], related_name='shared_orgs', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for problem', max_length=256),
        ),
    ]
