# Generated by Django 4.0.4 on 2022-05-30 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_alter_testcase_output_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='shortname',
            field=models.SlugField(help_text="This field is used to separate different problems from each other, similar to `problem code'. Only letters [A-Z], numbers [0-9], underscores (_) or hyphens (-) allowed. Max length is 128 characters. e.g. BIGNUM-PRIME, MAZE-3,... ", max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
