# Generated by Django 4.0.4 on 2022-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_userprofile_first_name_and_more'),
        ('organization', '0002_initial'),
        ('problem', '0005_alter_problem_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_privated_to_orgs',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='published_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='banned_users',
            field=models.ManyToManyField(blank=True, help_text='Bans the selected users from submitting to this problem.', to='userprofile.userprofile', verbose_name='personae non gratae'),
        ),
        migrations.AddField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Publish date of problem', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_organization_private',
            field=models.BooleanField(default=False, help_text='If private only added, organizations may see and submit to the problem.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='If this option was False, only users added above (authors, collab,...) may see the problem. If this option was True, this problem is public (anyone can see and submit).', verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='authors',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may view, edit the problem, and will be listed as Authors on the Problem Detail page.', related_name='authored_problems', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='collaborators',
            field=models.ManyToManyField(blank=True, default=[], help_text="These users may view, edit the problem, but won't be listed as Authors on the Problem Detail page.", related_name='collaborated_problems', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='organizations',
            field=models.ManyToManyField(blank=True, default=[], to='organization.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reviewers',
            field=models.ManyToManyField(blank=True, default=[], help_text='These users may only view and make submissions to the problem', related_name='reviewed_problems', to='userprofile.userprofile'),
        ),
    ]
