# Generated by Django 4.0.3 on 2022-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problemtestprofile_zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.IntegerField(null=True, verbose_name='case position'),
        ),
    ]
