# Generated by Django 4.0.3 on 2022-04-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problem_content_alter_problem_shared_orgs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestdataprofile',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='test_profile', serialize=False, to='problem.problem', to_field='shortname'),
        ),
    ]
