# Generated by Django 4.0.3 on 2022-05-02 11:14

from django.db import migrations, models
import helpers.problem_data
import problem.models.problem_test_data
import problem.validators.problem_data_zip


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_rename_zipfile_problemtestprofile__zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestprofile',
            name='_zipfile',
            field=models.FileField(blank=True, null=True, storage=helpers.problem_data.ProblemDataStorage(), upload_to=problem.models.problem_test_data.problem_directory_file, validators=[problem.validators.problem_data_zip.ProblemDataZipFileValidator()]),
        ),
    ]
