# Generated by Django 4.0.3 on 2022-05-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_alter_problemtestprofile__zipfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtestprofile',
            old_name='_zipfile',
            new_name='zipfile',
        ),
    ]
