# Generated by Django 4.0.3 on 2022-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_rename__zipfile_problemtestprofile_zipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_circuit',
            field=models.BooleanField(default=False, verbose_name='short circuit'),
        ),
    ]
