# Generated by Django 4.0.3 on 2022-05-02 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_problem_short_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.FloatField(default=100, help_text="Points awarded for problem completion. Points are displayed with a 'p' suffix if partial.", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='points'),
        ),
    ]
