# Generated by Django 4.0.3 on 2022-05-04 11:24

import django.core.validators
from django.db import migrations, models
import helpers.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_problem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, storage=helpers.problem_data.ProblemPDFStorage(), upload_to=helpers.problem_data.problem_directory_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
