# Generated by Django 4.0.3 on 2022-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_problem_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='partial',
            field=models.BooleanField(default=False, verbose_name='allows partial points'),
        ),
    ]
