# Generated by Django 4.0.4 on 2022-06-17 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]+$', 'Contest identifier must starts with a letter, contains only lowercase letters.'), django.core.validators.MinLengthValidator(4)], verbose_name='contest identifier'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='use_clarifications',
            field=models.BooleanField(default=False, help_text='Allow participants to use the clarification system.', verbose_name='Allow clarification request'),
        ),
    ]
