# Generated by Django 4.0.4 on 2022-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='scoreboard_cache_duration',
            field=models.PositiveIntegerField(default=0, help_text='How long (seconds) should scoreboard will be cached. Set to 0 to disable', verbose_name='scoreboard cache timeout'),
        ),
    ]
