# Generated by Django 4.0.4 on 2022-06-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_short_name'),
        ('userprofile', '0003_alter_userprofile_display_organization'),
        ('compete', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-id'], 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AddField(
            model_name='contest',
            name='published',
            field=models.BooleanField(default=False, help_text='Allow users beside authors, collaborators, reviewers to see the contest', verbose_name='contest published'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Allow contest data to be viewed by anyone', verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may register to the contest', to='organization.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='private_contestants',
            field=models.ManyToManyField(blank=True, help_text='If private, only these users may register to the contest', related_name='private_contestants+', to='userprofile.userprofile', verbose_name='private contestants'),
        ),
    ]
