# Generated by Django 4.0.4 on 2022-06-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_contestproblem_attempted_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'ordering': ['-id'], 'verbose_name': 'contest submission', 'verbose_name_plural': 'contest submissions'},
        ),
    ]
