# Generated by Django 4.0.4 on 2022-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_contest_scoreboard_cache_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='frozen_time',
            field=models.DateTimeField(blank=True, help_text="Timestamp to freeze results, if 'enable_frozen' is True", null=True, verbose_name='freeze after'),
        ),
    ]
