# Generated by Django 4.0.4 on 2022-07-25 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_alter_contest_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9\\-_]+$', 'Contest identifier must starts with a letter, contains only letters (lowercase), digits, and dashes.'), django.core.validators.MinLengthValidator(4)], verbose_name='contest identifier'),
        ),
    ]
