# Generated by Django 4.0.4 on 2022-06-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_contestpartcipantbestsubmissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestPartcipantBestSubmissions',
            new_name='ContestParticipantBestSubmission',
        ),
    ]
