# Generated by Django 4.0.4 on 2022-06-24 11:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_alter_contest_format_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='frozen_format_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='contest format specific data'),
        ),
    ]
