# Generated by Django 4.0.4 on 2022-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0006_contestparticipation_frozen_format_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='frozen_time',
            field=models.DateTimeField(blank=True, help_text='time when frozen data was last written', null=True, verbose_name='frozen time'),
        ),
    ]
