# Generated by Django 4.0.4 on 2022-06-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0006_rename_contestpartcipantbestsubmissions_contestparticipantbestsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipantbestsubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submission', to='compete.contestparticipation', verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='contestparticipantbestsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submission', to='compete.contestproblem', verbose_name='problem'),
        ),
        migrations.AlterField(
            model_name='contestparticipantbestsubmission',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_submission', to='compete.contestsubmission', verbose_name='submission'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipantbestsubmission',
            unique_together={('participant', 'problem')},
        ),
    ]
