# Generated by Django 4.0.4 on 2022-06-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0007_alter_contestparticipantbestsubmission_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipantbestsubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='compete.contestparticipation', verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='contestparticipantbestsubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='compete.contestproblem', verbose_name='problem'),
        ),
    ]
