# Generated by Django 4.0.4 on 2022-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0007_contest_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='standing_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='standing date'),
        ),
        migrations.AddField(
            model_name='contest',
            name='standing_outdated_reason',
            field=models.CharField(blank=True, default='', help_text='reason for why Standing is outdated', max_length=255, verbose_name='standing outdated reason'),
        ),
    ]
