# Generated by Django 4.0.4 on 2022-06-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0008_alter_contestparticipantbestsubmission_participant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestParticipantBestSubmission',
        ),
    ]
