# Generated by Django 4.0.4 on 2022-06-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0009_delete_contestparticipantbestsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipantBestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='compete.contest', verbose_name='contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='compete.contestparticipation', verbose_name='participant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='compete.contestproblem', verbose_name='problem')),
                ('submission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_submission', to='compete.contestsubmission', verbose_name='submission')),
            ],
            options={
                'verbose_name': "participant's best submission",
                'verbose_name_plural': "participant's best submissions",
                'unique_together': {('participant', 'problem')},
            },
        ),
    ]
