# Generated by Django 4.0.4 on 2022-06-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0010_contestparticipantbestsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestParticipantBestSubmission',
        ),
    ]
