# Generated by Django 4.0.4 on 2022-06-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0013_alter_contest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestparticipation',
            options={'ordering': ['-id'], 'verbose_name': 'contest participation', 'verbose_name_plural': 'contest participations'},
        ),
    ]
