# Generated by Django 4.0.4 on 2022-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Organization name shown in URL', max_length=128, unique=True, verbose_name='organization slug'),
        ),
    ]
