# Generated by Django 4.0.4 on 2022-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(help_text='Displayed beside user name during contests', max_length=20, unique=True, verbose_name='short name'),
        ),
    ]
