# Generated by Django 4.0.4 on 2022-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
    ]
