# Generated by Django 4.0.4 on 2022-08-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organization_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('create_root_organization', 'Create root Organization'), ('move_organization_anywhere', 'Move organization to others parents or let it become root itself.')), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
    ]
