# Generated by Django 4.0.4 on 2022-08-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_code_prompt',
            field=models.CharField(blank=True, help_text='Organization access code prompt', max_length=255, null=True, verbose_name='access code prompt'),
        ),
    ]
