# Generated by Django 4.0.4 on 2022-06-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created'], 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
    ]
