# Generated by Django 4.0.4 on 2022-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_alter_problem_partial_alter_problem_short_circuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestprofile',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom-PY3', 'Custom checker (Py3)'), ('custom-CPP17', 'Custom checker (C++17)'), ('interactive-CPP17', 'Interactive checker (C++17)')], max_length=20, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('floats', 'Floats'), ('floatsabs', 'Floats (absolute)'), ('floatsrel', 'Floats (relative)'), ('rstripped', 'Non-trailing spaces'), ('sorted', 'Unordered'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line'), ('custom-PY3', 'Custom checker (Py3)'), ('custom-CPP17', 'Custom checker (C++17)'), ('interactive-CPP17', 'Interactive checker (C++17)')], max_length=20, verbose_name='checker'),
        ),
    ]
